### ISSUE TITLE
"Connection refused" After Certificate Renewal

### ISSUE THREAD

**Issue by AndrewPaglusch** [linuxserver/docker-swag#225]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When a Let's Encrypt certificate is scheduled for renewal, it should renew and reload Nginx so that the new certificate is used. Incoming connections to Swag should continue to work.

## Current Behavior
When a Let's Encrypt certificate is renewed, Nginx (inside Swag) refuses incoming connections on ports 80 and 443.

I host multiple different instances of [Seafile](https://www.seafile.com/en/home/) behind Swag. Most on dedicated servers. All are configured the same. This issue affects them all. When a certificate is renewed automatically by Swag, the backend application (Seafile, in this case) goes down. A quick `docker restart swag` gets everything up and running right away.

```
[root@redacted-seafile01 ~]# curl -viLk http://localhost
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

```
[root@redacted-seafile01 ~]# docker exec -t swag curl -viLk http://localhost:80
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying ::1:80...
* Immediate connect fail for ::1: Network unreachable
* Failed to connect to localhost port 80 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
```

## Steps to Reproduce

1. Install swag (`image: ghcr.io/linuxserver/swag`)
2. Configure DNS challenge with Cloudflare
3. Set up Seafile in same `docker-compose.yml` file
4. Configure Swag to proxy to Seafile:

**Swag Seafile Config**
```
[root@redacted-seafile01 ~]# cat /opt/docker/swag/config/nginx/site-confs/cloud.redacted.com.conf
server {
	listen 80;
	listen [::]:80;
	server_name cloud.redacted.com;
	return 301 https://$host$request_uri;
}

# main server block
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name cloud.redacted.com;

	# all ssl related config moved to ssl.conf
	include /config/nginx/ssl.conf;

	#allow large uploads
	client_max_body_size 0;

	location / {
	        proxy_pass http://seafile:80;
		proxy_request_buffering off;
		proxy_buffering off;
	        proxy_set_header Host $host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto $scheme;
	}
}
```

5. Restart Swag so that certificate will be generated
6. Wait for renewal (multiple weeks). Nginx/Swag will refuse incoming TCP connections on ports 80 and 443 from inside Swag, inside Seafile, on the host, and from external sources. I have yet to test manually triggering a renewal to see if this can be reproduced more quickly.

## Environment
**OS:** Rocky Linux 8.4
**CPU architecture:** x86_64
**How docker service was installed:**
```
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install docker-ce
```

**OS Information**
```
[root@redacted-seafile01 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

**Kernel**
```
[root@redacted-seafile01 ~]# uname -r
4.18.0-305.10.2.el8_4.x86_64
```

**Docker Version**
```
[root@redacted-seafile01  ~]# docker -v
Docker version 20.10.7, build f0df350
```

**Docker Images Used**
```
[root@redacted-seafile01 ~]# docker images
REPOSITORY                 TAG       IMAGE ID       CREATED         SIZE
ghcr.io/linuxserver/swag   latest    3c1fab54ecd2   2 months ago    395MB
seafileltd/seafile-mc      latest    5653eeeb2d86   7 months ago    931MB
mariadb                    10.1      895244a22f37   11 months ago   352MB
memcached                  1.5.6     855fdf342eda   4 years ago     58.6MB
```

**Letsencrypt Logs**
```
<------------------------------------------------->
cronjob running on Mon Apr 4 02:08:00 CDT 2022
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/redacted.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for redacted.com and cloud.redacted.com
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Waiting 10 seconds for DNS changes to propagate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations, all renewals succeeded:
  /etc/letsencrypt/live/redacted.com/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

## Command used to create docker container (run/create/compose/screenshot)
```
version: '3'
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: always
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=redacted.com
      - VALIDATION=dns
      - CERTPROVIDER=letsencrypt
      - SUBDOMAINS=cloud
      - ONLY_SUBDOMAINS=yes
      - DNSPLUGIN=cloudflare #swag/config/dns-conf

  seafile-db:
    image: mariadb:10.1
    #command: --skip-grant-tables
    container_name: seafile-db
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./seafile/seafile-db/data:/var/lib/mysql

  seafile-memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256

  seafile-app:
    image: seafileltd/seafile-mc:latest
    container_name: seafile-app
    volumes:
      - ./seafile/seafile-app/data:/shared   # Requested, specifies the path to Seafile data persistent store.
      - ./seafile/seafile-app/hosts:/etc/hosts
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=REDACTED
      - SEAFILE_ADMIN_EMAIL=REDACTED
      - SEAFILE_ADMIN_PASSWORD=REDACTED
      - SEAFILE_SERVER_HOSTNAME=cloud.redacted.com
    depends_on:
      - seafile-db
      - seafile-memcached
```

## Docker logs
```
[root@redacted-seafile01 ~]# docker logs --tail 100 swag
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=America/Chicago
URL=redacted.com
SUBDOMAINS=cloud
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=yes
VALIDATION=dns
CERTPROVIDER=letsencrypt
DNSPLUGIN=cloudflare
EMAIL=
STAGING=

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d cloud.redacted.com
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing...
**** The following nginx confs have different version dates than the defaults that are shipped. ****
**** This may be due to user customization or an update to the defaults. ****
**** To update them to the latest defaults shipped within the image, delete these files and restart the container. ****
**** If they are user customized, check the date version at the top and compare to the upstream changelog via the link. ****
/config/nginx/ssl.conf
/config/nginx/proxy.conf
/config/nginx/nginx.conf

[cont-init.d] 70-templates: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
```

**Comment by AndrewPaglusch** [comment]
@aptalca Thank you for pointing that out to me. That makes this problem even more interesting, since after the renewal (and restart), Nginx doesn't accept any new connections until I restart the entire Swag container.

**Comment by aptalca** [comment]
Not sure what to tell you. I got a bunch of servers running swag with dns validation and I have never experienced that issue. We did have some issues a while back with nginx getting stuck during a restart, but I'm pretty sure we fixed those with a rather sledgehammer-like approach: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/services.d/nginx/run#L3-L13

You can try restarting nginx inside the container with the same commands from after renewal and see if it's somehow getting stuck

**Comment by AndrewPaglusch** [comment]
I will go ahead and try restarting Nginx inside the container when this happens again. How do you suggest I do that using the init system used in the Swag container?

**Comment by aptalca** [comment]
Although, if you were having issues with nginx getting stuck, the s6 supervisor would have at least logged messages about it. I haven't noticed such log messages in a long time so I'm assuming the bug that caused it has long been fixed upstream.

**Comment by aptalca** [comment]
`docker exec -it swag s6-svc -h /var/run/s6/services/nginx` is the equivalent of what the script uses

**Comment by AndrewPaglusch** [comment]
Thank you. I will give that a try next time this happens and report back. If I can find a way to reproduce the problem **without** waiting 30 days for the renewal, I will be posting here a lot sooner with my findings.

**Comment by aptalca** [comment]
you can force a renewal every night if you edit the renewal script inside the container and add `--force-renewal` after certbot renew

**Comment by AndrewPaglusch** [comment]
Ok, I've added that to one of my Swag containers. I will post results once I have them.

**Comment by AndrewPaglusch** [comment]
Adding `--force-renewal` reproduced the issue. I tried running `docker exec -it swag s6-svc -h /var/run/s6/services/nginx` to restart Nginx in the container, but that didn't seem to resolve the problem for me.

I'm not sure if this is a result of the `s6-svc -h` command I just ran, or a result of the LE renewal, but I just discovered is that Nginx isn't even running in the container.
```
root@f8ce8d2f6599:/# ps aux | grep nginx
root       484  0.0  0.0    188     0 ?        S    Apr04   0:00 s6-supervise nginx
root       789  0.0  0.0   1572   368 pts/0    R+   08:13   0:00 grep nginx
```

I can start it up like this. This brings the site back online.
```
root@f8ce8d2f6599:/# /bin/s6-svstat /var/run/s6/services/nginx/
down (exitcode 0) 22161 seconds, normally up, ready 22161 seconds

root@f8ce8d2f6599:/# /bin/s6-svc -u /var/run/s6/services/nginx

root@f8ce8d2f6599:/# /bin/s6-svstat /var/run/s6/services/nginx/
up (pid 843) 4 seconds
```

Please let me know if there's any more information you'd like me to grab.

**Comment by aptalca** [comment]
Wait, I just realized your issue. Your renewal config has this pre-hook:
`pre_hook = if ps aux | grep [n]ginx: > /dev/null; then s6-svc -d /var/run/s6/services/nginx; fi`

That is the reason nginx stops prior to renewal, and then never comes up, because `s6-svc -h` is `nohup`, which means it only restarts a running service, but not start a stopped one.

I have no idea how that pre-hook ended up in your renewal conf, but it should not be there. I just checked a few of mine also doing dns validation with cloudflare and none of them have this.

It could be that maybe you ran a manual certbot command that messed it up, or you edited a file you weren't supposed to (like the one named `donoteditthisfile.conf`).

Anyhow, first make sure that you are on the latest swag image (your renewal conf suggests you're not, as it's listing an older certbot version). Then delete the folder `/etc/letsencrypt` in your config folder. Upon a restart, it will get a brand new cert and the hooks should be configured properly after that.

Keep in mind that letsencrypt will send you an email in a couple of months about cert expiration, ignore that, because that will be for your current cert which you will be deleting.

**Comment by AndrewPaglusch** [comment]
Good find! I can assure you I made no edits to the LE config on any of these servers. Perhaps this was an old config that I've been carrying along across Swag upgrades?

Anyway, I will perform the steps you recommended and post back with results. Thank you!

**Comment by AndrewPaglusch** [comment]
This problem is resolved. Thank you, @aptalca, for all of your help!

**Comment by aptalca** [comment]
Good to hear. Let us know if it ever happens again and we'll try to troubleshoot further. However, I'm quite convinced (and hopeful) it was an edge case and not a current bug.

**Comment by lo-decibel** [comment]
I can confirm I had exactly the same problem. Starting nginx as per @AndrewPaglusch's instructions worked, a permanent fix was to delete `/etc/letsencrypt` and restart as per your instructions @aptalca. I'm not sure if it this was a fluke occurrence or a bug.

**Comment by lo-decibel** [comment]
> I can confirm I had exactly the same problem.

It seems like I spoke too soon. On subsequent restarts, the problem persists, and deleting `/etc/letsencrypt` didn't do anything. But restarting nginx manually did resolve the problem. I will do some tinkering, see if I can reproduce the error, and post in a new thread as this is likely a different issue (I'm using duckdns and I don't have the pre-hook in my renewal conf like @AndrewPaglusch.)

**Comment by guny74** [comment]
I have the same issue.... I completly renew the docker container from scratch, but same error.... using http validation (ports are open) @lo-decibel  how can I restart the nginx manually inside the container ?

**Comment by lo-decibel** [comment]
> I have the same issue.... I completly renew the docker container from scratch, but same error.... using http validation (ports are open) @lo-decibel  how can I restart the nginx manually inside the container ? `docker exec -it swag s6-svc -h /var/run/s6/services/nginx` seams not to work (only on older version)
> 
>  Using Docker Image  Version 2.3.0

Not sure. I'm not using SWAG anymore so I can't offer any suggestions. But I do remember in the past I think I needed to have both 80 and 443 mapped (but 80 didn't have to be externally forwarded). Not sure about now.

**Comment by aptalca** [comment]
Please open a new issue and fill out the issue template

**Comment by brenojac** [comment]
> I suspected, by reading the docs at https://docs.linuxserver.io/general/swag#docker-compose, that Let's encrypt certs could be the problem and switched to ZeroSSL:

Thanks. I just did it https://github.com/linuxserver/docker-swag/issues/353
