### ISSUE TITLE
TimeZone is not set correctly in the SWAG container

### ISSUE THREAD

**Issue by zhorvath83** [linuxserver/docker-swag#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I've set a custom timezone in the docker-compose, so I would expect that if I get the current time on the container's console with the date command, it should not be UTC time. 

In case of other containers (eg. linuxserver/qbittorrent) the time zone setting works well (but that is Ubuntu based opposed to Alpine).

## Current Behavior
If I get the current time on the container's console with the date command, it is UTC time. 
This causes problems in fail2ban detection (in case of logs mounted from outside).

I have tried to mount host's etc/timezone and etc/localtime but the result was the same:
_volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"_

## Steps to Reproduce

1. `docker exec swag date`
2. the output is: "Sat Nov 14 23:13:26 UTC 2020"
3. `date`
4. the output is: "Sun Nov 15 00:13:29 CET 2020"

## Environment
**OS**: raspbian
**CPU architecture:** arm64
**How docker service was installed:** from Raspbian Repository

## Command used to create docker container (compose)
```
  swag:
    depends_on:
      - authelia
    image: linuxserver/swag:latest
    container_name: swag
    networks:
      - bridge
    ports:
      - 2443:443
      - 2080:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - URL=mydomain.eu
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - ONLY_SUBDOMAINS=false
      - MAXMINDDB_LICENSE_KEY=licensekey
    volumes:
      - /var/lib/docker/volumes/swag_data:/config
      - /var/lib/docker/volumes/bitwarden_data/bwlog:/config/log/bitwarden:ro
      - /var/lib/docker/volumes/homeassistant_data/home-assistant.log:/config/log/homeassistant/home-assistant.log:ro
      - /var/lib/docker/volumes/authelia_data/authelia.log:/config/log/authelia/authelia.log:ro
      - /var/log/auth.log:/config/log/openmediavault/auth.log:ro
      - /var/lib/docker/volumes/pihole_data/log/pihole.log:/config/log/pihole/pihole.log:ro
    labels:
      - "diun.enable=true"
    restart: always

```
## Docker logs

```
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
chown: changing ownership of '/config/log/authelia/authelia.log': Read-only file system
chown: changing ownership of '/config/log/homeassistant/home-assistant.log': Read-only file system
chown: changing ownership of '/config/log/openmediavault/auth.log': Read-only file system
chown: changing ownership of '/config/log/pihole/pihole.log': Read-only file system
chown: changing ownership of '/config/log/bitwarden/bitwarden.log': Read-only file system
chown: changing ownership of '/config/log/bitwarden': Read-only file system
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=Europe/Budapest
URL=mydomain.eu
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=
STAGING=

SUBDOMAINS entered, processing
Wildcard cert for mydomain.eu will be requested
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
chown: changing ownership of '/config/log/authelia/authelia.log': Read-only file system
chown: changing ownership of '/config/log/homeassistant/home-assistant.log': Read-only file system
chown: changing ownership of '/config/log/openmediavault/auth.log': Read-only file system
chown: changing ownership of '/config/log/pihole/pihole.log': Read-only file system
chown: changing ownership of '/config/log/bitwarden/bitwarden.log': Read-only file system
chown: changing ownership of '/config/log/bitwarden': Read-only file system
chmod: changing permissions of '/config/log/authelia/authelia.log': Read-only file system
chmod: changing permissions of '/config/log/homeassistant/home-assistant.log': Read-only file system
chmod: changing permissions of '/config/log/openmediavault/auth.log': Read-only file system
chmod: changing permissions of '/config/log/pihole/pihole.log': Read-only file system
chmod: changing permissions of '/config/log/bitwarden': Read-only file system
chmod: changing permissions of '/config/log/bitwarden/bitwarden.log': Read-only file system
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
```

**Comment by aptalca** [comment]
Works fine here: 
```
aptalca@odroidc2:~$ docker run -d --rm --name test -e TZ=Europe/Budapest ghcr.io/linuxserver/swag:arm64v8-latest
85070e5b810d451c6e09ce07e10540238d293f4e9f973147db51edfbf7ba5c0a
aptalca@odroidc2:~$ docker exec -it test date
Sun Nov 15 00:46:25 CET 2020
```

**Comment by zhorvath83** [comment]
I'm very sorry, but I forgot to clarify that I use Raspberry Pi OS ((Lite) 32 bit version), so I use the armhf image.

**Comment by aptalca** [comment]
yup can confirm the arm32v7 image doesn't set the time correctly. We'll look into it.

**Comment by aptalca** [comment]
I tested it with the official alpine images `arm64v8/alpine` and `arm32v7/alpine` and they exhibit the same behavior as ours, where it works on arm64, but not arm32. This is indeed an upstream issue. Likely with the alpine tzdata package.

Setting the timezone via the TZ variable is a function of the tzdata package.

Please report it to alpine on their gitlab issues.

**Comment by aptalca** [comment]
Actually, I did see an open issue about tzdata and tacked this on as well: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12057#note_124235

**Comment by zhorvath83** [comment]
Thank you for your investigation.

**Comment by aptalca** [comment]
This is fixed in the latest

**Comment by YouveGotMeowxy** [comment]
I'm having an issue with the logs showing UTC time even though I've specified my local TZ.

Here's my current Swag compose (I set it in both the environment var as well as the mount):

```
 swag:
    image: ghcr.io/linuxserver/swag:latest
    environment:
      TZ: ${TZ}
      URL: my.domain
      SUBDOMAINS: wildcard
      FILE__EMAIL: /run/secrets/CloudFlare-Email
      PUID: 1000
      PGID: 1000
      VALIDATION: dns
      ONLY_SUBDOMAINS: 'true'
      DNSPLUGIN: 'cloudflare'
      FILE__MAXMINDDB_LICENSE_KEY: /run/secrets/Maxmind-Key
      DOCKER_MODS: linuxserver/mods:swag-ffmpeg|linuxserver/mods:swag-geoip2influx
      # Config Ref: https://github.com/linuxserver/docker-mods/tree/swag-geoip2influx
      # Currently removed |linuxserver/mods:swag-imagemagick from above mods, due to it breaking Swag.
      INFLUX_HOST: influxdb
      INFLUX_HOST_PORT: 8086
      INFLUX_DATABASE: nginx
      INFLUX_USER: nginx
      FILE__INFLUX_PASS: /run/secrets/Influx-PW
      SEND_NGINX_LOGS: 'true'
      GEOIP2INFLUX_LOG_LEVEL: info
    volumes:
      - /opt/docker/configs/Swag/config:/config:rw
      - /mnt/d/Logs/swag:/config/log:rw
      - /etc/localtime:/etc/localtime:ro
    #cap_add:
    #  - NET_ADMIN # Optional: Required for fail2ban to modify iptables (ignored in swarm mode)
    ports:
      - 443:443
    secrets:
      - Influx-PW
      - CloudFlare-Email
      - Maxmind-Key
    deploy:
      mode: global
      restart_policy:
        condition: any
    networks:
      - om
```

Then in my logs, it still shows UTC time.. (note that my current time was 10:51 am but logs are showing 3:51 pm)

My basic log shows:

> today at 10:51:11 AM  GEOIP2INFLUX 25/Jun/2021 15:51:11 :: INFO :: Starting geoip2influx..
> today at 10:51:12 AM  GEOIP2INFLUX 25/Jun/2021 15:51:12 :: INFO :: Starting log parsing

and my error log shows:

> 2021/06/25 16:08:05 [error] 689#689: *298 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: bitwarden.*, request: "GET

**Comment by Roxedus** [comment]
Please open a new issue, this one was closed last year... @YouveGotMeowxy
