### ISSUE TITLE
[BUG] 2.6.0-ls232 not starting

### ISSUE THREAD

**Issue by golles** [linuxserver/docker-swag#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`2.6.0-ls232` isn't starting, `2.6.0-ls231` is fine.

### Steps To Reproduce

I've updated from `2.6.0-ls231` to `2.6.0-ls232` (latest) and noticed the container isn't starting

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- How docker service was installed:
  - Followed this guide: https://docs.docker.com/engine/install/ubuntu/
  - And `sudo apt install docker-compose`
```

### CPU architecture

x86-64

### Docker creation

docker-compose.yaml

```yaml
...
  swag:
    container_name: swag
    restart: unless-stopped
    image: linuxserver/swag:2.6.0-ls232
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_DIR}/swag:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=${PROXY_CERT_EMAIL}
      - URL=${PROXY_CERT_URL}
      - SUBDOMAINS=${PROXY_CERT_SUBDOMAINS}
      - ONLY_SUBDOMAINS=${PROXY_CERT_ONLY_SUBDOMAINS}
      - VALIDATION=${PROXY_CERT_VALIDATION}
      - DNSPLUGIN=${PROXY_CERT_DNSPLUGIN}
      - PROPAGATION=${PROXY_CERT_PROPAGATION}
      - STAGING=${PROXY_CERT_STAGING}
      - DOCKER_MODS=linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=${PROXY_MAXMIND_LICENSE_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
...
```

.env
```
PGID=1000
PUID=1000
TZ=Europe/Amsterdam
PROXY_CERT_URL=***
PROXY_CERT_EMAIL=***
PROXY_CERT_SUBDOMAINS=wildcard
PROXY_CERT_ONLY_SUBDOMAINS=false
PROXY_CERT_EXTRA_DOMAINS=*.local.***
PROXY_CERT_VALIDATION=dns
PROXY_CERT_DNSPLUGIN=directadmin
PROXY_CERT_PROPAGATION=120
PROXY_CERT_STAGING=false
PROXY_MAXMIND_LICENSE_KEY=***
```

### Container logs

```bash
❯ dcl swag
Attaching to swag
swag                  | [mod-init] Attempting to run Docker Modification Logic
swag                  | [mod-init] Adding linuxserver/mods:swag-maxmind to container
swag                  | [mod-init] Downloading linuxserver/mods:swag-maxmind from lscr.io
swag                  | [mod-init] Installing linuxserver/mods:swag-maxmind
swag                  | [mod-init] linuxserver/mods:swag-maxmind applied to container
swag                  | [migrations] started
swag                  | [migrations] 01-nginx-site-confs-default: skipped
swag                  | [migrations] done
swag                  | ───────────────────────────────────────
swag                  | 
swag                  |       ██╗     ███████╗██╗ ██████╗ 
swag                  |       ██║     ██╔════╝██║██╔═══██╗
swag                  |       ██║     ███████╗██║██║   ██║
swag                  |       ██║     ╚════██║██║██║   ██║
swag                  |       ███████╗███████║██║╚██████╔╝
swag                  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
swag                  | 
swag                  |    Brought to you by linuxserver.io
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | To support the app dev(s) visit:
swag                  | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag                  | 
swag                  | To support LSIO projects visit:
swag                  | https://www.linuxserver.io/donate/
swag                  | 
swag                  | ───────────────────────────────────────
swag                  | GID/UID
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | User UID:    1000
swag                  | User GID:    1000
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | using keys found in /config/keys
swag                  | Variables set:
swag                  | PUID=1000
swag                  | PGID=1000
swag                  | TZ=Europe/Amsterdam
swag                  | URL=***
swag                  | SUBDOMAINS=wildcard
swag                  | EXTRA_DOMAINS=
swag                  | ONLY_SUBDOMAINS=false
swag                  | VALIDATION=dns
swag                  | CERTPROVIDER=
swag                  | DNSPLUGIN=directadmin
swag                  | EMAIL=***
swag                  | STAGING=false
swag                  | 
swag                  | Please set the DNSPLUGIN variable to one of the following:
swag                  |
```

**Comment by Roxedus** [comment]
We also need the values for most of the environment variables.

**Comment by golles** [comment]
I think the important ones are in the log already, are there any others I should share?

**Comment by Roxedus** [comment]
The log does not show the whole picture, like formatting etc.

**Comment by WesSec** [comment]
Also experiencing this issue with the same console output OP posted (no more output after the DNS plugin line). 

I rolled back to 230 and it started fine again. For debugging purposes I pulled latest again, but now it keeps starting up correctly.

**Comment by golles** [comment]
> The log does not show the whole picture, like formatting etc.

Ok, I added my env variables to the issue.

**Comment by nemchik** [comment]
From inside the container, can you run `echo $PATH` and post the output here?
To get into the container you might need to run `docker exec -it swag bash` on the host.

**Comment by golles** [comment]
> From inside the container, can you run `echo $PATH` and post the output here? To get into the container you might need to run `docker exec -it swag bash` on the host.

```bash
root@9bb7b890c4c5:/# echo $PATH
/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by filler** [comment]
I noticed I was having similar issues.  Container hanging at the _"Please set the DNSPLUGIN variable to one of the following"_ log line, no certbot events firing in the container, no recent helpful logs.  👎 

I decided to follow this bug report to downgrade to ls230.  I noticed when pulling down ls230 to downgrade my docker runtime in my Synology that the PATH env var on the ls230 image had `/lsiopy/bin` in it while my latest image did not.  **Edited my existing broken ontainer config, prepended `/lsiopy/bin` into the PATH env var**, started the container back up, bam.  All good. 🎉 

```bash
2023-09-04T19:58:21.478336002Z [migrations] started
2023-09-04T19:58:21.483743665Z [migrations] 01-nginx-site-confs-default: skipped
2023-09-04T19:58:21.484163677Z [migrations] done
2023-09-04T19:58:21.567007393Z usermod: no changes
2023-09-04T19:58:21.568522186Z ───────────────────────────────────────
2023-09-04T19:58:21.568682873Z
2023-09-04T19:58:21.568725645Z       ██╗     ███████╗██╗ ██████╗
2023-09-04T19:58:21.568779908Z       ██║     ██╔════╝██║██╔═══██╗
2023-09-04T19:58:21.568831501Z       ██║     ███████╗██║██║   ██║
2023-09-04T19:58:21.568879668Z       ██║     ╚════██║██║██║   ██║
2023-09-04T19:58:21.568924066Z       ███████╗███████║██║╚██████╔╝
2023-09-04T19:58:21.568967432Z       ╚══════╝╚══════╝╚═╝ ╚═════╝
2023-09-04T19:58:21.569014348Z
2023-09-04T19:58:21.569052638Z    Brought to you by linuxserver.io
2023-09-04T19:58:21.569100933Z ───────────────────────────────────────
2023-09-04T19:58:21.569146849Z
2023-09-04T19:58:21.569184527Z To support the app dev(s) visit:
2023-09-04T19:58:21.570051317Z Certbot: https://supporters.eff.org/donate/support-work-on-certbot
2023-09-04T19:58:21.570549119Z
2023-09-04T19:58:21.570608797Z To support LSIO projects visit:
2023-09-04T19:58:21.570676800Z https://www.linuxserver.io/donate/
2023-09-04T19:58:21.570725106Z
2023-09-04T19:58:21.570763811Z ───────────────────────────────────────
2023-09-04T19:58:21.570809504Z GID/UID
2023-09-04T19:58:21.570852294Z ───────────────────────────────────────
2023-09-04T19:58:21.573991039Z
2023-09-04T19:58:21.574114074Z User UID:    1000
2023-09-04T19:58:21.574174999Z User GID:    1000
2023-09-04T19:58:21.574220421Z ───────────────────────────────────────
2023-09-04T19:58:21.574267555Z
2023-09-04T19:58:21.666987030Z using keys found in /config/keys
2023-09-04T19:58:21.888969189Z Variables set:
2023-09-04T19:58:21.889154744Z PUID=1000
2023-09-04T19:58:21.889223685Z PGID=1000
2023-09-04T19:58:21.889293159Z TZ=UTC
2023-09-04T19:58:21.889341134Z URL=nickflix.org
2023-09-04T19:58:21.889404162Z SUBDOMAINS=wildcard
2023-09-04T19:58:21.889463943Z EXTRA_DOMAINS=
2023-09-04T19:58:21.889544934Z ONLY_SUBDOMAINS=false
2023-09-04T19:58:21.889614457Z VALIDATION=dns
2023-09-04T19:58:21.889686238Z CERTPROVIDER=
2023-09-04T19:58:21.889743600Z DNSPLUGIN=route53
2023-09-04T19:58:21.889817414Z EMAIL=
2023-09-04T19:58:21.889860999Z STAGING=
2023-09-04T19:58:21.889918815Z
2023-09-04T19:58:26.748040109Z Using Let's Encrypt as the cert provider
2023-09-04T19:58:26.749266173Z SUBDOMAINS entered, processing
2023-09-04T19:58:26.749612965Z Wildcard cert for nickflix.org will be requested
2023-09-04T19:58:26.754329517Z No e-mail address entered or address invalid
2023-09-04T19:58:26.762305482Z dns validation via route53 plugin is selected
2023-09-04T19:58:26.762711812Z Certificate exists; parameters unchanged; starting nginx
2023-09-04T19:58:26.865668371Z The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
2023-09-04T19:58:26.872811725Z /config/nginx/ldap.conf exists.
2023-09-04T19:58:26.872909620Z         Please apply any customizations to /config/nginx/ldap-server.conf
2023-09-04T19:58:26.872983007Z         Ensure your configs are updated and remove /config/nginx/ldap.conf
2023-09-04T19:58:26.873062009Z         If you do not use this config, simply remove it.
2023-09-04T19:58:26.998575630Z **** The following active confs have different version dates than the samples that are shipped. ****
2023-09-04T19:58:26.998772052Z **** This may be due to user customization or an update to the samples. ****
2023-09-04T19:58:26.998832889Z **** You should compare the following files to the samples in the same folder and update them. ****
2023-09-04T19:58:26.998888728Z **** Use the link at the top of the file to view the changelog. ****
2023-09-04T19:58:26.998941013Z ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
2023-09-04T19:58:26.998996570Z │  old date  │  new date  │ path                                                                   │
2023-09-04T19:58:26.999049871Z ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
2023-09-04T19:58:26.999100609Z │ 2021-09-19 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
2023-09-04T19:58:26.999152510Z │ 2021-10-26 │ 2023-02-09 │ /config/nginx/proxy.conf                                               │
2023-09-04T19:58:26.999201255Z │ 2021-04-21 │ 2023-04-27 │ /config/nginx/authelia-location.conf                                   │
2023-09-04T19:58:26.999251275Z │ 2022-01-09 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
2023-09-04T19:58:26.999298729Z │ 2021-04-27 │ 2023-06-05 │ /config/nginx/site-confs/default.conf                                  │
2023-09-04T19:58:26.999348270Z │ 2021-05-28 │ 2023-04-27 │ /config/nginx/authelia-server.conf                                     │
2023-09-04T19:58:26.999396047Z │ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/overseerr.subdomain.conf                     │
2023-09-04T19:58:26.999458608Z │ 2023-02-09 │ 2023-04-27 │ /config/nginx/authentik-location.conf                                  │
2023-09-04T19:58:26.999507995Z │ 2023-02-09 │ 2023-04-27 │ /config/nginx/authentik-server.conf                                    │
2023-09-04T19:58:26.999554448Z │ 2020-06-02 │ 2022-08-20 │ /config/nginx/ldap-server.conf                                         │
2023-09-04T19:58:26.999601794Z └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
2023-09-04T19:58:27.026666380Z [custom-init] No custom files found, skipping...
2023-09-04T19:58:27.054850441Z crond[474]: crond (busybox 1.36.1) started, log level 5
2023-09-04T19:58:27.093659858Z [ls.io-init] done.
2023-09-04T19:58:27.224824524Z [04-Sep-2023 19:58:27] NOTICE: fpm is running, pid 473
2023-09-04T19:58:27.226165652Z [04-Sep-2023 19:58:27] NOTICE: ready to handle connections
2023-09-04T19:58:27.390065087Z Server ready
```

**Comment by j0nnymoe** [comment]
Synology user? I suspect the issue you're experiencing is this this: https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by golles** [comment]
> Synology user? I suspect the issue you're experiencing is this this: https://info.linuxserver.io/issues/2023-05-22-portainer/

In my case, it's not running on a Synology

**Comment by j0nnymoe** [comment]
> > Synology user? I suspect the issue you're experiencing is this this: https://info.linuxserver.io/issues/2023-05-22-portainer/
> 
> In my case, it's not running on a Synology

Are you running portainer?

**Comment by filler** [comment]
> Synology user? I suspect the issue you're experiencing is this this: https://info.linuxserver.io/issues/2023-05-22-portainer/

Yeah. Syno user here. 

Is Portainer the native Syno Web UI? Or something else? I only use the vanilla web UI, no supplemental helper wrappers. 

I tend to chase latest tag over time. Look like it broke moving up from >ls230. 🤙

**Comment by golles** [comment]
> > > Synology user? I suspect the issue you're experiencing is this this: https://info.linuxserver.io/issues/2023-05-22-portainer/
> > 
> > 
> > In my case, it's not running on a Synology
> 
> Are you running portainer? Or some auto updater?

I've portainer running for ease, but I use docker-compose to manage my containers

**Comment by j0nnymoe** [comment]
> > > > Synology user? I suspect the issue you're experiencing is this this: [info.linuxserver.io/issues/2023-05-22-portainer](https://info.linuxserver.io/issues/2023-05-22-portainer/)
> > > 
> > > 
> > > In my case, it's not running on a Synology
> > 
> > 
> > Are you running portainer? Or some auto updater?
> 
> I've portainer running for ease, but I use docker-compose to manage my containers

What are you using for updating? and when you say you're using docker-compose? do you mean stacks within portainer?

**Comment by golles** [comment]
I'm using the command line to update my containers.

**Comment by filler** [comment]
My method for updating is as follows:

1. A shell for loop in cli doing a docker pull for all containers
2. Stop containers 
3. Reset containers 
4. Start containers

**Comment by drizuid** [comment]
> My method for updating is as follows:
> 
> 1. A shell for loop in cli doing a docker pull for all containers
> 2. Stop containers in Syno UI
> 3. Reset containers in Syno UI
> 4. Start containers in Syno UI

for you, the problem (not something we can fix) was already posted above. This is a synology ui (and portainer ui) issue. You need to use docker run or docker compose to get around it. The OP has a different issue as they are using docker compose straight up.

**Comment by Platzii** [comment]
Had the same issue on my setup. Did some debugging and found that there was a change in the certbot DirectAdmin plugin that causes the issue.
Created a PR (#412) that should solve it.

(Note: you might need to delete `/config/etc/letsencrypt/cli.ini` if it has been persisted/mounted to disk)

**Comment by golles** [comment]
Thank you @Platzii 
I do have another issue now, I can't get the certs for my config.

I've logged in to my DirectAdmin panel and I could see 2 `TXT` records with the name `_acme-challenge` are present during the challenge.

```
swag                  | [mod-init] Attempting to run Docker Modification Logic
swag                  | [mod-init] Adding linuxserver/mods:swag-maxmind to container
swag                  | [mod-init] linuxserver/mods:swag-maxmind at sha256:bb158926d3ef7bc99993ba17f735a21b4826e1b72a89069f33a94358a2730b71 has been previously applied skipping
swag                  | [migrations] started
swag                  | [migrations] 01-nginx-site-confs-default: skipped
swag                  | [migrations] done
swag                  | usermod: no changes
swag                  | ───────────────────────────────────────
swag                  | 
swag                  |       ██╗     ███████╗██╗ ██████╗ 
swag                  |       ██║     ██╔════╝██║██╔═══██╗
swag                  |       ██║     ███████╗██║██║   ██║
swag                  |       ██║     ╚════██║██║██║   ██║
swag                  |       ███████╗███████║██║╚██████╔╝
swag                  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
swag                  | 
swag                  |    Brought to you by linuxserver.io
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | To support the app dev(s) visit:
swag                  | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag                  | 
swag                  | To support LSIO projects visit:
swag                  | https://www.linuxserver.io/donate/
swag                  | 
swag                  | ───────────────────────────────────────
swag                  | GID/UID
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | User UID:    1000
swag                  | User GID:    1000
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | using keys found in /config/keys
swag                  | chown: cannot dereference '/config/keys/letsencrypt': No such file or directory
swag                  | **** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
swag                  | **** The app may not work properly and we will not provide support for it. ****
swag                  | Variables set:
swag                  | PUID=1000
swag                  | PGID=1000
swag                  | TZ=Europe/Amsterdam
swag                  | URL=<redacted>.nl
swag                  | SUBDOMAINS=wildcard
swag                  | EXTRA_DOMAINS=
swag                  | ONLY_SUBDOMAINS=false
swag                  | VALIDATION=dns
swag                  | CERTPROVIDER=
swag                  | DNSPLUGIN=directadmin
swag                  | EMAIL=<redacted>
swag                  | STAGING=false
swag                  | 
swag                  | Using Let's Encrypt as the cert provider
swag                  | SUBDOMAINS entered, processing
swag                  | Wildcard cert for <redacted>.nl will be requested
swag                  | E-mail address entered: letsencrypt@golles.nl
swag                  | dns validation via directadmin plugin is selected
swag                  | Generating new certificate
swag                  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
swag                  | Requesting a certificate for <redacted>.nl and *.<redacted>.nl
swag                  | Unsafe permissions on credentials configuration file: /config/dns-conf/directadmin.ini
swag                  | Waiting 240 seconds for DNS changes to propagate
swag                  | 
swag                  | Certbot failed to authenticate some domains (authenticator: dns-directadmin). The Certificate Authority reported these problems:
swag                  |   Domain: <redacted>.nl
swag                  |   Type:   unauthorized
swag                  |   Detail: No TXT record found at _acme-challenge.<redacted>.nl
swag                  | 
swag                  |   Domain: <redacted>.nl
swag                  |   Type:   unauthorized
swag                  |   Detail: No TXT record found at _acme-challenge.<redacted>.nl
swag                  | 
swag                  | Hint: The Certificate Authority failed to verify the DNS TXT records created by --dns-directadmin. Ensure the above domains are hosted by this DNS provider, or try increasing --dns-directadmin-propagation-seconds (currently 240 seconds).
swag                  | 
swag                  | Some challenges have failed.
swag                  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
swag                  | ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/directadmin.ini file.
```

I did change the time from 120 to 240, but that's not helping

**Comment by golles** [comment]
Hmm, it might be a local issue with the TTL on my domain.

**Comment by golles** [comment]
Yep, was TTL. Sorry for bothering

**Comment by Uksa007** [comment]
@Platzii So this issue seems to have been rolled out into the latest production version, server won't start now have deleted /config/etc/letsencrypt/cli.ini still the same.

Any ideas how to get the server backup ?

using keys found in /config/keys
Variables set:
PUID=1000
PGID=1000
TZ=redacted
URL=redacted
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=redacted
STAGING=false

Please set the DNSPLUGIN variable to one of the following:
