### ISSUE TITLE
[BUG] 2.7.0 Breaks my reverse proxy. 2.6.0 works fine.

### ISSUE THREAD

**Issue by JacobTheEldest** [linuxserver/docker-swag#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Accessing a proxied URL does not return a page at all. No error returned to client.

### Expected Behavior

I should be able to access the services I have proxied.

### Steps To Reproduce

Update to 2.7.0 or latest as of  8pm Oct 3 2023.
Attempt to access a proxied URL

### Environment

```markdown
- OS: Ubuntu 22.04.3
- How docker service was installed: system repository
```

### CPU architecture

x86-64

### Docker creation

```bash
swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:2.6.0
    # image: lscr.io/linuxserver/swag:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
      - 81:81
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=redacted.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - CERTPROVIDER= # optional - defaults to letsencrypt
      - DNSPLUGIN=cloudflare # for DNS Validation. needs creds in /config/dns-conf
      - PROPAGATION= # optional
      - EMAIL=redacted@hotmail.com # for cert expiration notification
      - ONLY_SUBDOMAINS=false # optional
      - EXTRA_DOMAINS= # optional
      - STAGING=false # optional
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload #linuxserver/mods:universal-docker
    volumes:
      - ./swag/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - NET_ADMIN
```

### Container logs

```bash
$ docker-compose up swag

Starting swag ... done
Attaching to swag
swag                | [mod-init] Attempting to run Docker Modification Logic
swag                | [mod-init] Adding linuxserver/mods:swag-dashboard to container
swag                | [mod-init] linuxserver/mods:swag-dashboard at sha256:594c67a6b598c080f019ef64b7978d4408e451f88530293646e395d8324460a7 has been previously applied skipping
swag                | [mod-init] Adding linuxserver/mods:swag-auto-reload to container
swag                | [mod-init] linuxserver/mods:swag-auto-reload at sha256:9dbae5d11b0dab3c5825a700ea1933a606a81df6312186da0f167e6ed8b6039e has been previously applied skipping
swag                | [migrations] started
swag                | [migrations] 01-nginx-site-confs-default: skipped
swag                | [migrations] done
swag                | usermod: no changes
swag                | ───────────────────────────────────────
swag                |
swag                |       ██╗     ███████╗██╗ ██████╗
swag                |       ██║     ██╔════╝██║██╔═══██╗
swag                |       ██║     ███████╗██║██║   ██║
swag                |       ██║     ╚════██║██║██║   ██║
swag                |       ███████╗███████║██║╚██████╔╝
swag                |       ╚══════╝╚══════╝╚═╝ ╚═════╝
swag                |
swag                |    Brought to you by linuxserver.io
swag                | ───────────────────────────────────────
swag                |
swag                | To support the app dev(s) visit:
swag                | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag                |
swag                | To support LSIO projects visit:
swag                | https://www.linuxserver.io/donate/
swag                |
swag                | ───────────────────────────────────────
swag                | GID/UID
swag                | ───────────────────────────────────────
swag                |
swag                | User UID:    1000
swag                | User GID:    1000
swag                | ───────────────────────────────────────
swag                |
swag                | using keys found in /config/keys
swag                | Variables set:
swag                | PUID=1000
swag                | PGID=1000
swag                | TZ=America/New_York
swag                | URL=jacobsteward.me
swag                | SUBDOMAINS=wildcard
swag                | EXTRA_DOMAINS=
swag                | ONLY_SUBDOMAINS=false
swag                | VALIDATION=dns
swag                | CERTPROVIDER=
swag                | DNSPLUGIN=cloudflare
swag                | EMAIL=jacobtheeldest@gmail.com
swag                | STAGING=false
swag                |
swag                | Please set the DNSPLUGIN variable to one of the following:
swag                |
```

**Comment by hamlynt** [comment]
Can confirm same issue on Ubuntu 22.04, reverting to 2.6.0 worked as a temporary fix for me too.

**Comment by Roxedus** [comment]
This was fixed before the issue was filed, please update.

**Comment by cpaucar3** [comment]
Confirmed the latest image tag fixed it, thanks!

**Comment by JacobTheEldest** [comment]
I continued to have the same problem even now at 9:45 pm EST. But I noticed that I was using the lscr.io registry `image: lscr.io/linuxserver/swag:latest`. Switch to the docker hub latest tag `image: linuxserver/swag:latest` works fine.

Perhaps CI image pushes to the lscr.io registry take longer?

**Comment by nemchik** [comment]
`lscr.io/linuxserver/swag:latest` uses ghcr and currently points to https://github.com/linuxserver/docker-swag/pkgs/container/swag/133993884?tag=latest

`linuxserver/swag:latest` uses docker hub and currently points to https://hub.docker.com/layers/linuxserver/swag/latest/images/sha256-3c103b69b2abb8deb74226e823d68ee27509a5b582257afff6252f647ea264a6?context=explore

both are pushed within a few minutes of each other before a release is tagged on github in this repo, for example this one https://github.com/linuxserver/docker-swag/releases/tag/2.7.0-ls243 which is associated with the two images linked above.

If you're updating after noticing a release (or being notified of a release) you should be fine to use lscr (or ghcr). If you're trying to pull an update before the release on github, don't.

**Comment by LinkinsRepeater** [comment]
Unfortunately the issue is not resolved for me.

Since this update my reverse proxy just always ends up with Error code 522.

I'm running the latest branch.
Yesterday everything was running fine.
Weird part is, I re rolled back to a previous version and the issue persists.
Is it possible something was changed in the config? I didn't do anything from my side.
