### ISSUE TITLE
[BUG] SWAG won't start with Crowdsec mod

### ISSUE THREAD

**Issue by JPDVM2014** [linuxserver/docker-swag#552]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Will not complete startup. Throws Lua errors.

### Expected Behavior

Completes startup.

### Steps To Reproduce

Install with crowdsec mod. Try to start container.

### Environment

```markdown
- OS:Unraid 6.12.15
- How docker service was installed:CA Template
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='swag'
  --net='docker'
  --pids-limit 2048
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="HOST"
  -e HOST_CONTAINERNAME="swag"
  -e 'URL'='myurl.com'
  -e 'VALIDATION'='dns'
  -e 'SUBDOMAINS'='wildcard'
  -e 'CERTPROVIDER'='zerossl'
  -e 'DNSPLUGIN'='cloudflare'
  -e 'PROPAGATION'='60'
  -e 'EMAIL'=''
  -e 'ONLY_SUBDOMAINS'='false'
  -e 'EXTRA_DOMAINS'=''
  -e 'STAGING'='false'
  -e 'TZ'='America/New_York'
  -e 'CROWDSEC_API_KEY'=''
  -e 'CROWDSEC_LAPI_URL'='http://192.168.100.88:8083'
  -e 'CROWDSEC_F2B_DISABLE'='true'
  -e 'DOCKER_MODS'='linuxserver/mods:swag-dashboard | linuxserver/mods:swag-crowdsec | linuxserver/mods:swag-dbip'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '443:443/tcp'
  -p '8009:81/tcp'
  -p '80:80/tcp'
  -v '/mnt/docker_vm/appdata/swag':'/config':'rw'
  --cap-add=NET_ADMIN
  --no-healthcheck
  --log-opt max-size=50m
  --log-opt max-file=3 'lscr.io/linuxserver/swag'
```

### Container logs

```bash
[mod-init] Running Docker Modification Logic
[mod-init] Adding linuxserver/mods:swag-dashboard to container
[mod-init] Downloading linuxserver/mods:swag-dashboard from lscr.io
[mod-init] Installing linuxserver/mods:swag-dashboard
[mod-init] linuxserver/mods:swag-dashboard applied to container
[mod-init] Adding linuxserver/mods:swag-crowdsec to container
[mod-init] Downloading linuxserver/mods:swag-crowdsec from lscr.io
[mod-init] Installing linuxserver/mods:swag-crowdsec
[mod-init] linuxserver/mods:swag-crowdsec applied to container
[mod-init] Adding linuxserver/mods:swag-dbip to container
[mod-init] Downloading linuxserver/mods:swag-dbip from lscr.io
[mod-init] Installing linuxserver/mods:swag-dbip
[mod-init] linuxserver/mods:swag-dbip applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-swag-old-certbot-paths: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 3.3.0-ls370
Build-date: 2025-03-15T03:31:31+00:00
───────────────────────────────────────
    
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-04-13 │ 2024-12-17 │ /config/nginx/nginx.conf                                               │
│ 2023-08-13 │ 2024-12-06 │ /config/nginx/ssl.conf                                                 │
│ 2024-07-16 │ 2024-12-17 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf~
/config/nginx/site-confs/.default.conf.un~
Variables set:

    PUID=99

    PGID=100

    TZ=America/New_York

    URL=

    SUBDOMAINS=wildcard

    EXTRA_DOMAINS=

    ONLY_SUBDOMAINS=false

    VALIDATION=dns

    CERTPROVIDER=zerossl

    DNSPLUGIN=cloudflare

    EMAIL=

    STAGING=false

ZeroSSL is selected as the cert provider, registering cert with
SUBDOMAINS entered, processing
Wildcard cert for  will be requested
E-mail address entered: 
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
Applying the dbip mod...
**** Applying the SWAG dashboard mod... ****
**** Configuring CrowdSec nginx Bouncer ****
Applied the dbip mod
**** Adding goaccess to package install list ****
**** libmaxminddb already installed, skipping ****
**** The swag-dashboard conf has been updated ****
**** Compare the changes using the sample file: /config/nginx/proxy-confs/dashboard.subdomain.conf.sample
**** Applied the SWAG dashboard mod ****
**** Successfully configured CrowdSec nginx Bouncer  ****
[pkg-install-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
(1/17) Installing gettext-envsubst (0.22.5-r0)
(2/17) Installing libgomp (14.2.0-r4)
(3/17) Installing gettext-libs (0.22.5-r0)
(4/17) Installing gettext (0.22.5-r0)
(5/17) Installing goaccess (1.9.3-r0)
(6/17) Installing lua5.1-libs (5.1.5-r13)
(7/17) Installing lua5.1 (5.1.5-r13)
(8/17) Installing lua-resty-http (0.17.2-r0)
(9/17) Installing luajit (2.1_p20240815-r0)
(10/17) Installing lua-resty-lrucache (0.13-r1)
(11/17) Installing lua-resty-core (0.1.29-r0)
(12/17) Installing nginx-mod-http-lua (1.26.3-r0)
(13/17) Installing lua-resty-string (0.15-r0)
(14/17) Installing lua-sec (1.3.2-r0)
(15/17) Installing lua5.1-socket (3.1.0-r1)
(16/17) Installing lua5.1-sec (1.3.2-r0)
(17/17) Installing lua5.1-cjson (2.1.0-r11)
Executing busybox-1.37.0-r12.trigger
OK: 189 MiB in 239 packages
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2025/03/16 23:42:05 [emerg] 968#968: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
Server ready
2025/03/16 23:42:06 [emerg] 1048#1048: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
2025/03/16 23:42:07 [emerg] 1057#1057: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
2025/03/16 23:42:08 [emerg] 1066#1066: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
2025/03/16 23:42:09 [emerg] 1075#1075: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
2025/03/16 23:42:10 [emerg] 1084#1084: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1
```

**Comment by JPDVM2014** [comment]
I'm trying to copy the logs in so they are readable. The main error is 

2025/03/16 23:21:44 [emerg] 1084#1084: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1026003 instead of 1026002 in /etc/nginx/modules/30_http_lua.conf:1

**Comment by alleyu2** [comment]
Facing the exact same issue

**Comment by Yaff1e** [comment]
Same error here too

**Comment by Crash1602** [comment]
Same error here too

**Comment by jclendineng** [comment]
Downgrading to 3.2.0 does NOT work, interestingly meaning theres something downloaded with the latest build that's not overwritten by a downgrade.

**Comment by Crash1602** [comment]
> Downgrading to 3.2.0 does NOT work, interestingly meaning theres something downloaded with the latest build that's not overwritten by a downgrade.

Yes. I have also try an downgrade, but dosn´t work.

**Comment by laszlo462** [comment]
Another confirmation that downgrading does not work.  Following this.

**Comment by Crash1602** [comment]
I don't know if the bug was the reason, but 3.3.0-ls371 just came out. Unfortunately, it now has this error:

```
2025/03/17 15:26:21 [alert] 983#983: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
2025/03/17 15:26:22 [alert] 988#988: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
2025/03/17 15:26:23 [alert] 993#993: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
2025/03/17 15:26:24 [alert] 998#998: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
```

**Comment by emorgoch** [comment]
Getting the same thing. Same errors, same platform (Unraid 6.12.15)

**Comment by JPDVM2014** [comment]
> I don't know if the bug was the reason, but 3.3.0-ls371 just came out. Unfortunately, it now has this error:
> 
> ```
> 2025/03/17 15:26:21 [alert] 983#983: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
> 2025/03/17 15:26:22 [alert] 988#988: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
> 2025/03/17 15:26:23 [alert] 993#993: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
> 2025/03/17 15:26:24 [alert] 998#998: failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: /usr/share/lua/common/resty/core/base.lua:24: ngx_http_lua_module 0.10.27 required) in /config/nginx/nginx.conf:114
> ```
> 
> Plattform Debian 12 with Docker CE Standalone 27.5.1

Same here. I updated on a different server, and I no longer get the lua error with Crowdec, but now it won't start at all, even with all the mods removed.

**Comment by thespad** [comment]
TL;DR lua-resty-core package needs adding but it isn't compatible with version 0.10.28 of the lua nginx module because it has a hardcoded check for 0.10.27. I can patch the check but I'm not sure I want to. The nginx module was bumped yesterday in this commit https://gitlab.alpinelinux.org/alpine/aports/-/commit/696292c07a67b0977edb570917a1ba8ac4e14900 and so lua-resty-core needs bumping to 0.1.31 by the Alpine maintainers to match.

**Comment by drizuid** [comment]
https://discord.com/channels/354974912613449730/1351052262960795669

temp fix: `linuxserver/mods:swag-crowdsec:1.0.8`

**Comment by thespad** [comment]
> [discord.com/channels/354974912613449730/1351052262960795669](https://discord.com/channels/354974912613449730/1351052262960795669)
> 
> temp fix: `linuxserver/mods:swag-crowdsec:1.0.8`

`linuxserver/mods:swag-crowdsec-v1.0.8`

**Comment by thespad** [comment]
lua-resty-core has been updated by the Alpine packagers so the mod should now be working again.

**Comment by Crash1602** [comment]
Thanks for the quick fix. The Crowdsec mod is working as usual again.

**Comment by Kaotic** [comment]
The issue seems to have reappeared with new `nginx-mod-http-lua (1.28.2-r0)`

```
Linuxserver.io version: 5.3.0-ls436
Build-date: 2026-02-03T19:48:44+00:00
```

```
**** Configuring CrowdSec nginx Bouncer ****
**** Successfully configured CrowdSec nginx Bouncer  ****
[pkg-install-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.22/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.22/community/x86_64/APKINDEX.tar.gz
(1/16) Installing gettext-envsubst (0.24.1-r0)
(2/16) Installing libgomp (14.2.0-r6)
(3/16) Installing gettext-libs (0.24.1-r0)
(4/16) Installing gettext (0.24.1-r0)
(5/16) Installing lua5.1-libs (5.1.5-r13)
(6/16) Installing lua5.1 (5.1.5-r13)
(7/16) Installing lua-resty-http (0.17.2-r0)
(8/16) Installing luajit (2.1_p20240815-r1)
(9/16) Installing lua-resty-lrucache (0.13-r1)
(10/16) Installing lua-resty-core (0.1.31-r0)
(11/16) Installing nginx-mod-http-lua (1.28.2-r0)
(12/16) Installing lua-resty-string (0.15-r0)
(13/16) Installing lua-sec (1.3.2-r0)
(14/16) Installing lua5.1-socket (3.1.0-r1)
(15/16) Installing lua5.1-sec (1.3.2-r0)
(16/16) Installing lua5.1-cjson (2.1.0-r11)
Executing busybox-1.37.0-r20.trigger
OK: 195 MiB in 237 packages
```

`2026/02/06 13:11:18 [emerg] 901#901: module "/var/lib/nginx/modules/ngx_http_lua_module.so" version 1028002 instead of 1028000 in /etc/nginx/modules/30_http_lua.conf:1`

**Comment by corelabjoe** [comment]
Good day @Roxedus looks like this issue still persists. Can you please re-open it?
